# publish.yml

name: "Publish"

on:
  release:
    types: ["published"]

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest
    environment:
      name: publish
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and setup Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build
        run: uv build

      - name: Import test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl -- python -c "import rgbxmastree"

      - name: Import test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz -- python -c "import rgbxmastree"

      - name: Publish
        run: uv publish --trusted-publishing always
